import { expect, test, type Page, type TestInfo } from '@playwright/test';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

type Verification = { description: string; check: () => Promise<void> };
type DocStep = { description: string; image: string; checks: string[] };

/** Every documented step must pass its checks and its screenshot comparison. */
export class TestStepHelper {
  private steps: DocStep[] = [];

  constructor(private page: Page, private info: TestInfo) {}

  async step(name: string, description: string, verifications: Verification[]) {
    const id = `${String(this.steps.length).padStart(3, '0')}-${name.replace(/[^a-z0-9-]/gi, '-')}`;
    const filename = `${id}-${this.info.project.name}.png`;
    await test.step(description, async () => {
      for (const verification of verifications) {
        await test.step(verification.description, verification.check);
      }
      await this.page.mouse.move(0, 0);
      await expect(this.page).toHaveScreenshot(filename);
      this.steps.push({
        description,
        image: `./screenshots/${filename}`,
        checks: verifications.map((verification) => verification.description)
      });
    });
  }

  generateDocs(title: string, description: string) {
    // Each browser project owns a file, so parallel workers cannot overwrite it.
    const filename = this.info.project.name === 'mobile-chromium'
      ? 'README.md'
      : `README.${this.info.project.name}.md`;
    const sections = this.steps.map((step) =>
      `## ${step.description}\n\n![${step.description}](${step.image})\n\n` +
      `**Verifications:**\n\n${step.checks.map((check) => `- [x] ${check}`).join('\n')}\n` +
      '- [x] Screenshot matches the committed baseline (zero differing pixels)'
    );
    writeFileSync(join(dirname(this.info.file), filename),
      `<!-- Generated by the E2E test. Do not edit by hand. -->\n\n# ${title}\n\n` +
      `${description}\n\nViewport: ${this.info.project.name}.\n\n${sections.join('\n\n')}\n`
    );
  }
}
